FROM elixir:1.15-alpine

RUN apk add make
RUN apk add build-base

WORKDIR /app

RUN mkdir /app/apps
RUN mkdir /app/config

COPY ./apps /app/apps
COPY ./config /app/config
COPY ./mix.exs /app

COPY ./.docker/admin_panel_entry_point.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/*

RUN mix deps.get

RUN mix local.hex

RUN mix archive.install hex phx_new

EXPOSE 4000

ENTRYPOINT ["admin_panel_entry_point.sh"]