FROM elixir:1.15-alpine

RUN apk add make
RUN apk add build-base

WORKDIR /app

RUN mkdir /app/apps
RUN mkdir /app/config

COPY ./apps /app/apps
COPY ./config /app/config
COPY ./mix.exs /app

COPY ./.docker/dev_node_api_entry_point.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/*

RUN mix deps.get

RUN apk update && apk upgrade
RUN apk add --no-cache sqlite 

RUN mkdir /home/bundles

RUN cp -R /app/apps/http_adapters/assets/b_an /home/bundles/b_an
RUN cp -R /app/apps/http_adapters/assets/b_wi /home/bundles/b_wi
RUN cp -R /app/apps/http_adapters/assets/b_li /home/bundles/b_li

RUN mix local.hex

EXPOSE 8080

ENTRYPOINT ["dev_node_api_entry_point.sh"]