FROM elixir:1.15-alpine

RUN apk add make
RUN apk add build-base

WORKDIR /app

RUN mkdir /app/apps
RUN mkdir /app/config

COPY ./apps /app/apps
COPY ./config /app/config
COPY ./mix.exs /app

COPY ./.docker/dev_node_websocket_device.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/*

RUN mix deps.get

RUN mix local.hex

EXPOSE 8081

ENTRYPOINT ["dev_node_websocket_device.sh"]