FROM elixir:1.15-alpine

RUN apk add make
RUN apk add build-base

WORKDIR /app

RUN mkdir /app/apps
RUN mkdir /app/config

COPY ./apps /app/apps
COPY ./config /app/config
COPY ./mix.exs /app

RUN mix deps.get

RUN apk update && apk upgrade
RUN apk add --no-cache sqlite 

RUN mkdir /home/bundles

RUN cp -R /app/apps/http_adapters/assets/b_an /home/bundles/b_an
RUN cp -R /app/apps/http_adapters/assets/b_wi /home/bundles/b_wi
RUN cp -R /app/apps/http_adapters/assets/b_li /home/bundles/b_li

CMD ["mix", "cmd", "--app", "http_adapters", "mix", "test", "--color"]