FROM elixir:1.15-alpine

RUN apk add make
RUN apk add build-base

WORKDIR /app

RUN mkdir /app/apps
RUN mkdir /app/config

COPY ./apps /app/apps
COPY ./config /app/config
COPY ./mix.exs /app

RUN mix deps.get

CMD ["mix", "cmd", "--app", "http_adapters", "mix", "test", "--color"]